modLoader = "javafml"
loaderVersion = "[47,)"
license = "GPL-3.0"

[[mods]]
modId = "lomka"
version = "0.4.1"
displayName = "Lomka"
authors = "Starlev"
description = """Applies various, compatible optimizations to improve perfomance and stability. Ready for client, server or both uses!"""
logoFile = "assets/lomka/icon.png"

[[dependencies.lomka]]
modId = "forge"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.lomka]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
