modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="lomka"
version="0.2.1"
displayName="Lomka"
authors="Starlev"
description='''A less powerful optimization mod. Performs various optimizations: chunks, culling, opengl, nbt and network.'''
logoFile="icon.png"

[[dependencies.lomka]]
modId="neoforge"
type="required"
versionRange="[21.11.38-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.lomka]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
