modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="lomka"
version="${mod_version}"
displayName="Lomka"
authors="Starlev"
description='''A less powerful optimization mod. Performs various optimizations: chunks, culling, opengl, nbt and network.'''
logoFile="icon.png"

[[dependencies.lomka]]
modId="neoforge"
type="required"
versionRange="[21.11.39-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.lomka]]
modId="minecraft"
type="required"
versionRange="[26.1,27)"
ordering="NONE"
side="BOTH"
